/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PM.MEJ;

import java.io.InputStream;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author llEarlzll
 */
public class ProductTable extends javax.swing.JFrame {

    /**
     * Creates new form ProductTable
     */
    public ProductTable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TLname = new javax.swing.JTextField();
        BAdd = new javax.swing.JButton();
        rep = new javax.swing.JButton();
        lMessage = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TFname = new javax.swing.JTextField();
        IMG = new javax.swing.JLabel();
        BGDImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(375, 430));
        setMinimumSize(new java.awt.Dimension(375, 430));
        getContentPane().setLayout(null);

        tblProduct.setFont(new java.awt.Font("Courier New", 0, 11)); // NOI18N
        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name"
            }
        ));
        tblProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProduct);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(25, 267, 310, 105);

        jLabel2.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("First Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(25, 112, 70, 24);

        jLabel3.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Last Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(25, 151, 70, 24);

        TLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TLnameActionPerformed(evt);
            }
        });
        getContentPane().add(TLname);
        TLname.setBounds(120, 155, 100, 24);

        BAdd.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        BAdd.setText("Add");
        BAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAddActionPerformed(evt);
            }
        });
        getContentPane().add(BAdd);
        BAdd.setBounds(80, 210, 57, 23);

        rep.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        rep.setText("IReport");
        rep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repActionPerformed(evt);
            }
        });
        getContentPane().add(rep);
        rep.setBounds(199, 210, 110, 23);

        lMessage.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lMessage.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(lMessage);
        lMessage.setBounds(25, 238, 306, 18);

        jLabel4.setFont(new java.awt.Font("Britannic Bold", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("GPN MACHINE SHOP");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(66, 6, 296, 56);

        TFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFnameActionPerformed(evt);
            }
        });
        getContentPane().add(TFname);
        TFname.setBounds(120, 116, 100, 24);

        IMG.setBackground(new java.awt.Color(255, 204, 51));
        IMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PM/MEJ/GPN Logo.png"))); // NOI18N
        getContentPane().add(IMG);
        IMG.setBounds(230, 68, 113, 115);

        BGDImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PM/MEJ/GPN bgd.PNG"))); // NOI18N
        getContentPane().add(BGDImage);
        BGDImage.setBounds(0, 0, 360, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAddActionPerformed
        // TODO add your handling code here:
        if(SQLite.openDB()){
            String fname = TFname.getText();
            String last = TLname.getText();
            
            String values = "'"+fname+"','"+last+"'";
            SQLite.createpro("ProductTable", values);           
        }
        
        lMessage.setText("");
        DefaultTableModel model=(DefaultTableModel)tblProduct.getModel();
        if(!TFname.getText().trim().equals("")){
            model.addRow(new Object[]{TFname.getText(),TLname.getText()});
          
        }else {
            lMessage.setText("Name Fields should not be left blank!");
        }
        
        SQLite.closeDB();
    }//GEN-LAST:event_BAddActionPerformed

    private void tblProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) tblProduct.getModel();
        TFname.setText(model.getValueAt(tblProduct.getSelectedRow(), 1).toString());
        TLname.setText(model.getValueAt(tblProduct.getSelectedRow(), 2).toString());
    }//GEN-LAST:event_tblProductMouseClicked

    private void TFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFnameActionPerformed

    private void TLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TLnameActionPerformed

    private void repActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repActionPerformed
        // TODO add your handling code here:
        try {
            if(SQLite.openDB()) {
                String report1 = ("GPNReport1.jrxml");
                InputStream file = getClass() .getResourceAsStream(report1);
                Helper.Report.viewReport(file);
                SQLite.closeDB();
            }
        }
        catch(Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_repActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAdd;
    private javax.swing.JLabel BGDImage;
    private javax.swing.JLabel IMG;
    private javax.swing.JTextField TFname;
    private javax.swing.JTextField TLname;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lMessage;
    private javax.swing.JButton rep;
    private javax.swing.JTable tblProduct;
    // End of variables declaration//GEN-END:variables
}
